name: CI Pipeline

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          lfs: true
      - name: Build
        run: make
        timeout-minutes: 10
