name: Build Release and Push
on:
  push:
    tags:
      - "*"
jobs:
  build-push-docker:
    name: ${{ matrix.image }} - ${{ matrix.arch }} docker build push
    runs-on: ${{ fromJSON('{"arm64":"buildjet-2vcpu-ubuntu-2204-arm","amd64":"ubuntu-22.04"}')[matrix.arch] }}
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Configure DockerHub
        uses: ./.github/actions/configure-dockerhub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      - name: Publish
        run: make docker-push VERSION=$GITHUB_REF_NAME TAG_SUFFIX=-${{ matrix.arch }}
  push-docker-manifests:
    runs-on: ubuntu-22.04
    needs:
      - build-push-docker
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Configure DockerHub
        uses: ./.github/actions/configure-dockerhub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      - name: Publish
        run: make push-manifests VERSION=$GITHUB_REF_NAME
