name: Build Release and Push
on:
  push:
    tags:
      - "*"
jobs:
  build-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          lfs: true
      - name: Configure DockerHub
        uses: ./.github/actions/configure-dockerhub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      - name: Publish
        run: make docker-push VERSION=$GITHUB_REF_NAME
